name: PR Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.11.x'
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.0.2
      - run: pnpm i
      - run: pnpm build
